name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
        continue-on-error: true
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          # Add any other environment variables your app needs
      
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp -r . deploy/
          cd deploy
          # Remove unnecessary files
          rm -rf .git .github node_modules tests
          # Install production dependencies only
          npm ci --production
          # Create Elastic Beanstalk configuration files if needed
          mkdir -p .ebextensions
          echo "option_settings:
            aws:elasticbeanstalk:container:nodejs:
              NodeVersion: 18.x
            aws:elasticbeanstalk:application:environment:
              NODE_ENV: production" > .ebextensions/nodecommand.config
          # Create Procfile for EB
          echo "web: npm start" > Procfile
          # Zip the deployment package
          zip -r ../deploy.zip .
          cd ..
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: "backend-${{ github.run_number }}-${{ github.sha }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300
      
      - name: Send deployment notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Backend Deployment Status
          SLACK_MESSAGE: 'Backend deployed to ${{ secrets.EB_ENVIRONMENT_NAME }} - ${{ job.status }}'
          SLACK_FOOTER: 'GitHub Actions'
        continue-on-error: true